# Generated by Django 5.0.2 on 2024-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorías/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-id'],
            },
        ),
    ]
