# Generated by Django 5.0.2 on 2024-05-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('sistemas', '0002_remove_sistema_categoria_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sistemas',
            field=models.ManyToManyField(blank=True, to='sistemas.sistema', verbose_name='Sistemas'),
        ),
    ]
