# Generated by Django 5.0.2 on 2024-05-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.PositiveSmallIntegerField(verbose_name='Teléfono')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
            ],
            options={
                'verbose_name': 'Solicitud_Soporte',
                'verbose_name_plural': 'Solicitud_Soportes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.PositiveSmallIntegerField(verbose_name='Teléfono')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Solicitud_Servicio',
                'verbose_name_plural': 'Solicitud_Servicios',
                'ordering': ['-id'],
            },
        ),
    ]
