# Generated by Django 5.0.2 on 2024-05-15 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_servicio_tipo'),
        ('solicitud', '0002_initial'),
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_servicio',
            name='id_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='solicitud_soporte',
            name='id_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.soporte', verbose_name='Plan Soporte'),
        ),
    ]
