# Generated by Django 5.0.2 on 2024-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('Especializados', 'Especializados'), ('Online', 'Online'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo'),
        ),
    ]
