# Generated by Django 5.0.2 on 2024-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Online', 'Online'), ('Especializados', 'Especializados')], max_length=50, verbose_name='Tipo'),
        ),
    ]
