# Generated by Django 5.0.2 on 2024-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Especialista', 'Especialista'), ('Cliente', 'Cliente')], default='Cliente', max_length=50, verbose_name='Rol'),
        ),
    ]
