# Generated by Django 5.0.2 on 2024-05-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Especialista', 'Especialista'), ('Administrador', 'Administrador')], default='Cliente', max_length=50, verbose_name='Rol'),
        ),
    ]
