# Generated by Django 5.0.2 on 2024-05-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='soporte/', verbose_name='Imagen')),
                ('servicios', models.ManyToManyField(to='servicios.servicio', verbose_name='Servicios Asociados')),
            ],
            options={
                'verbose_name': 'Soporte',
                'verbose_name_plural': 'Soportes',
                'ordering': ['-id'],
            },
        ),
    ]
