# Generated by Django 5.0.2 on 2024-05-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='categoria_id',
        ),
    ]
